household <- read.table("household_power_consumption.txt", sep=";", head=TRUE)
household$Date <- as.Date(household$Date,"%d/%m/%Y")
householdSub <- subset(household, Date >= as.Date("2007-02-01") & Date <= as.Date("2007-02-02"))
householdSub$DateTime <- as.POSIXct(paste(householdSub$Date, householdSub$Time), format="%Y-%m-%d %H:%M:%S")
png("plot3.png")
with(householdSub, plot(DateTime, as.numeric(gsub(",", ".", gsub("\\.", "", householdSub$Sub_metering_1)))/1000,type="n", ylab="Energy Sub Metering"))
lines(householdSub$DateTime,as.numeric(gsub(",", ".", gsub("\\.", "", householdSub$Sub_metering_1)))/1000)
lines(householdSub$DateTime,as.numeric(gsub(",", ".", gsub("\\.", "", householdSub$Sub_metering_2)))/1000, col="red")
lines(householdSub$DateTime,as.numeric(gsub(",", ".", gsub("\\.", "", householdSub$Sub_metering_3))), col="blue")
legend("topright", lty=1, col=c("black","red","blue"), legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3")) 
dev.off()