household <- read.table("household_power_consumption.txt", sep=";", head=TRUE)
household$Date <- as.Date(household$Date,"%d/%m/%Y")
householdSub <- subset(household, Date >= as.Date("2007-02-01") & Date <= as.Date("2007-02-02"))
householdSub$DateTime <- as.POSIXct(paste(householdSub$Date, householdSub$Time), format="%Y-%m-%d %H:%M:%S")
png("plot4.png")
par(mfrow = c(2,2), mar=c(4,4,2,1), oma=c(0,0,2,0))
with(householdSub, {
plot(DateTime, as.numeric(gsub(",", ".", gsub("\\.", "", Global_active_power)))/1000, type="n", ylab="Global active power(kilowatts)")
lines(DateTime,as.numeric(gsub(",", ".", gsub("\\.", "", Global_active_power)))/1000)
plot(DateTime, as.numeric(gsub(",", ".", gsub("\\.", "", Voltage)))/1000,type="n", ylab="Voltage")
lines(DateTime,as.numeric(gsub(",", ".", gsub("\\.", "", Voltage)))/1000)
plot(DateTime, as.numeric(gsub(",", ".", gsub("\\.", "", Sub_metering_1)))/1000,type="n", ylab="Energy Sub Metering")
lines(DateTime,as.numeric(gsub(",", ".", gsub("\\.", "", Sub_metering_1)))/1000)
lines(DateTime,as.numeric(gsub(",", ".", gsub("\\.", "", Sub_metering_2)))/1000, col="red")
lines(DateTime,as.numeric(gsub(",", ".", gsub("\\.", "", Sub_metering_3))), col="blue")
legend("topright", lty=1, col=c("black","red","blue"), legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"))
plot(DateTime, Global_reactive_power,type="n")
lines(householdSub$DateTime,householdSub$Global_reactive_power)
})
dev.off()